name: Blockwork
main: no.blockwork.blockwork.Blockwork
version: ${project.version}
#database: true # Todo: Switch to Bukkit's native database engine?
depend: [WorldEdit]
softdepend: [AntiCheat,VanishNoPacket,PerformanceMonitor,dynmap]

author: Jckf
website: http://www.minecraft.no/

permissions:
   blockwork.admin:
      description: Gives administrator access to Blockwork functions.
      default: op
      children:
         blockwork.admin.allow: true
         blockwork.admin.deny: true
         blockwork.supermod.allow: true
         blockwork.mod.allow: true
         blockwork.user.allow: true

   blockwork.supermod:
      description: Gives super moderator access to Blockwork functions.
      default: false
      children:
         blockwork.supermod.allow: true
         blockwork.supermod.deny: true
         blockwork.mod.allow: true
         blockwork.user.allow: true

   blockwork.mod:
      description: Gives moderator access to Blockwork functions.
      default: false
      children:
         blockwork.mod.allow: true
         blockwork.mod.deny: true
         blockwork.user.allow: true

   blockwork.user:
      description: Gives user access to Blockwork functions.
      default: false
      children:
         blockwork.user.allow: true
         blockwork.user.deny: true

   blockwork.guest:
      description: Gives guest access to Blockwork functions.
      default: false
      children:
         blockwork.guest.allow: true
         blockwork.guest.deny: true

commands:
   kick:
      description: Kicks the given player with an optional message.
      usage: /<command> [player] [reason]
      permission: blockwork.mod.allow

   ban:
      description: Bans the given user with an optional message.
      usage: /<command> [player] [reason]
      permission: blockwork.mod.allow

   guest:
      description: Sets a user's primary group to "Awaiting activation".
      usage: /<command> [player]
      permission: blockwork.mod.allow

   user:
      description: Sets a user's primary group to "Registered".
      usage: /<command> [player]
      permission: blockwork.mod.allow

   mod:
      description: Sets a user's primary group to "Super moderator".
      usage: /<command> [player]
      permission: blockwork.mod.allow

   admin:
      description: Sets a user's primary group to "Administrator".
      usage: /<command> [player]
      permission: blockwork.admin.allow

   reg:
      description: Lets a user go from "Awaiting activation" to "Registered".
      usage: /<command> [secret]
      permission: blockwork.guest.allow

   group:
      description: Group management.
      usage: /<command> [invite/accept/reject/join/list/leave/kick] [player]
      permission: blockwork.user.allow

   friend:
      description: Friend management.
      usage: /<command> [add/remove/list] [player]
      permission: blockwork.user.allow

   tools:
      description: Toggle tools.
      usage: /<command>
      permission: blockwork.mod.allow

   protect:
      description: Set block ownership.
      usage: /<command> [player]
      permission: blockwork.mod.allow

   chown:
      description: Change block ownership.
      usage: /<command> [player]
      permission: blockwork.mod.allow

   free:
      description: Remove block ownership.
      usage: /<command>
      permission: blockwork.mod.allow

   tp:
      description: Teleport to another player.
      usage: /<command> [player]
      permission: blockwork.mod.allow

   tph:
      description: Teleport another player to yourself.
      usage: /<command> [player]
      permission: blockwork.mod.allow

   goto:
      description: Teleport to coordinates.
      usage: /<command> <x> <y> <z>
      permission: blockwork.mod.allow

   setspawn:
      description: Changes default spawn location for current world.
      usage: /<command>
      permission: blockwork.admin.allow

   tpb:
      description: Teleport back to where you were before using /tp.
      usage: /<command>
      permission: blockwork.mod.allow

   fly:
      description: Toggle fly mode.
      usage: /<command>
      permission: blockwork.mod.allow

   mob:
      description: Spawn monsters.
      usage: /<command> [monster type] [count]
      permission: blockwork.mod.allow

   killall:
      description: Kills living entities.
      usage: /<command> [radius]
      permission: blockwork.mod.allow
